services:
  app:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SQL_INIT_MODE: ${SQL_INIT_MODE}
      JPA_HIBERNATE_DDL_AUTO: ${JPA_HIBERNATE_DDL_AUTO}
      JPA_HIBERNATE_DIALECT: ${JPA_HIBERNATE_DIALECT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    ports:
      - 8080:8080
    volumes:
      - ./uploads:/app/uploads
